In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [12]:
cd /content/drive/My Drive/dataset

/content/drive/My Drive/dataset


In [13]:
ls

 bengal_data/      content/                  'hijab girl.rar'   LJSpeech-1.1/
 Bengali_img.zip  'Copy of Bengali_img.zip'   input/


In [0]:
cp Bengali_img.zip /content/data

In [15]:
cd /content/

/content


In [16]:
ls

data/  drive/  sample_data/


In [17]:
cd data

/content/data


In [18]:
ls

Bengali_img.zip


In [19]:
!unzip Bengali_img.zip

Archive:  Bengali_img.zip
   creating: Bengali Ethnicity/
   creating: Bengali Ethnicity/Bengali Female/
  inflating: Bengali Ethnicity/Bengali Female/download (2).jpg  
  inflating: Bengali Ethnicity/Bengali Female/gfhfbw4ek9wiheznisiidjw5hhmydzvg6xzutlkg5avbgbqq9e1utqks0ax6yuxq-.jpg  
  inflating: Bengali Ethnicity/Bengali Female/istockphoto-610118916-612x612.jpg  
  inflating: Bengali Ethnicity/Bengali Female/-2019-bangladeshi-police-on-january-9-used-water-cannon-to-disperse-10000-striking-garment-workers-who-were-blocking-a-major-highway-in-a-fourth-day-of-industrial-action-an-official-said-credit-mamunur-rashidalamy-live-news-R_.jpg  
  inflating: Bengali Ethnicity/Bengali Female/00077509.jpg  
  inflating: Bengali Ethnicity/Bengali Female/002564bc674514b6daea08.jpg  
  inflating: Bengali Ethnicity/Bengali Female/01_Garment-worker_201114_0003-1024x682.jpg  
  inflating: Bengali Ethnicity/Bengali Female/0264_Bangladesh_2009_PeterCaton_Bangladesh_35797.jpg  
  inflating: Bengali Et

In [20]:
ls

'Bengali Ethnicity'/   Bengali_img.zip


In [21]:
pwd

'/content/data'

In [22]:
import pandas as pd
import numpy as np
import os
import keras
import matplotlib.pyplot as plt
from keras.layers import Dense,GlobalAveragePooling2D
from keras.applications import MobileNet
from keras.preprocessing import image
from keras.applications.mobilenet import preprocess_input
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.optimizers import Adam

Using TensorFlow backend.


In [29]:
base_model=MobileNet(weights='imagenet',include_top=False) #imports the mobilenet model and discards the last 1000 neuron layer.

x=base_model.output
x=GlobalAveragePooling2D()(x)
x=Dense(1024,activation='relu')(x) #we add dense layers so that the model can learn more complex functions and classify for better results.
x=Dense(1024,activation='relu')(x) #dense layer 2
x=Dense(512,activation='relu')(x) #dense layer 3
preds=Dense(2,activation='softmax')(x) #final layer with softmax activation

/usr/local/lib/python3.6/dist-packages/keras_applications/mobilenet.py:207: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '


In [0]:
model=Model(inputs=base_model.input,outputs=preds)
#specify the inputs
#specify the outputs
#now a model has been created based on our architecture

In [0]:
for layer in model.layers[:20]:
    layer.trainable=False
for layer in model.layers[20:]:
    layer.trainable=True

In [32]:
train_datagen=ImageDataGenerator(preprocessing_function=preprocess_input) #included in our dependencies

train_generator=train_datagen.flow_from_directory('Bengali Ethnicity', # this is where you specify the path to the main data folder
                                                 target_size=(224,224),
                                                 color_mode='rgb',
                                                 batch_size=32,
                                                 class_mode='categorical',
                                                 shuffle=True)

Found 4351 images belonging to 2 classes.


In [33]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
# Adam optimizer
# loss function will be categorical cross entropy
# evaluation metric will be accuracy

step_size_train=train_generator.n//train_generator.batch_size
model.fit_generator(generator=train_generator,
                   steps_per_epoch=step_size_train,
                   epochs=5)

Epoch 1/5


/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:742: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))


 18/135 [===>..........................] - ETA: 1:34 - loss: 1.0186 - acc: 0.6476

/usr/local/lib/python3.6/dist-packages/PIL/Image.py:2496: DecompressionBombWarning: Image size (139489119 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  DecompressionBombWarning)


 47/135 [=========>....................] - ETA: 58s - loss: 0.6225 - acc: 0.7620

/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 33685504 bytes but only got 0. Skipping tag 4
  " Skipping tag %s" % (size, len(data), tag))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 47185920 bytes but only got 0. Skipping tag 4
  " Skipping tag %s" % (size, len(data), tag))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 0. Skipping tag 3
  " Skipping tag %s" % (size, len(data), tag))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2359296 bytes but only got 0. Skipping tag 5
  " Skipping tag %s" % (size, len(data), tag))
/usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py:725: UserWarning: Possibly corrupt EXIF data.  Expecting to re

135/135 [==============================] - 86s 640ms/step - loss: 0.4120 - acc: 0.8324
Epoch 2/5
135/135 [==============================] - 81s 600ms/step - loss: 0.1964 - acc: 0.9250
Epoch 3/5
135/135 [==============================] - 81s 599ms/step - loss: 0.1537 - acc: 0.9391
Epoch 4/5
135/135 [==============================] - 82s 604ms/step - loss: 0.1515 - acc: 0.9504
Epoch 5/5
135/135 [==============================] - 80s 590ms/step - loss: 0.0931 - acc: 0.9687


In [0]:
model.save('mobBD.h5')

In [0]:
model.save('mobBD.model')

In [46]:
from keras.preprocessing import image

test = image.load_img('Bengali Ethnicity/Bengali Female/0001.jpg',
                      target_size=(224, 224))
test = image.img_to_array(test)
test = np.expand_dims(test, axis=0)

print(model.predict(test))
print(train_generator.class_indices)
#actually female

[[7.126579e-04 9.992874e-01]]
{'Bengali Female': 0, 'Bengali Male': 1}


In [47]:
from keras.preprocessing import image

test = image.load_img('Bengali Ethnicity/Bengali Female/68302657.jpg',
                      target_size=(224, 224))
test = image.img_to_array(test)
test = np.expand_dims(test, axis=0)

print(model.predict(test))
print(train_generator.class_indices)
#actually female

[[1.4684182e-04 9.9985313e-01]]
{'Bengali Female': 0, 'Bengali Male': 1}


In [49]:
from keras.preprocessing import image

test = image.load_img('Bengali Ethnicity/Bengali Male/10R.jpg',
                      target_size=(224, 224))
test = image.img_to_array(test)
test = np.expand_dims(test, axis=0)

print(model.predict(test))
print(train_generator.class_indices)
#actually male

[[2.9779514e-04 9.9970216e-01]]
{'Bengali Female': 0, 'Bengali Male': 1}


In [50]:

from keras.preprocessing import image

test = image.load_img('Bengali Ethnicity/Bengali Male/bangladeshi young men.jpg',
                      target_size=(224, 224))
test = image.img_to_array(test)
test = np.expand_dims(test, axis=0)

print(model.predict(test))
print(train_generator.class_indices)
#actually male

[[5.4797740e-04 9.9945205e-01]]
{'Bengali Female': 0, 'Bengali Male': 1}


In [52]:

from keras.preprocessing import image

test = image.load_img('Bengali Ethnicity/Bengali Female/11454888.jpg',
                      target_size=(224, 224))
test = image.img_to_array(test)
test = np.expand_dims(test, axis=0)

print(model.predict(test))
print(train_generator.class_indices)
#actually female

[[3.5559793e-04 9.9964440e-01]]
{'Bengali Female': 0, 'Bengali Male': 1}
